title: Singapore Together
url: "https://www.singaporetogether.gov.sg" 
favicon: /images/SG.ico

# Site colors
colors:
  primary-color: '#de3c4b'
  secondary-color: '#38415c'
  media-colors:
    - title: media-color-one
      color: '#de3c4b'
    - title: media-color-two
      color: '#ef616f'
    - title: media-color-three
      color: '#de3c4b'
    - title: media-color-four
      color: '#38415c'
    - title: media-color-five
      color: '#de3c4b'

resources_name: media-centre
future: true
shareicon: /images/sg-together-600x600.jpg
google-tag-manager: GTM-T7BHXPN

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: test test

staging: https://mccy-sgt-staging.netlify.app
prod: https://mccy-sgt-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
